### PR TITLE
feat: Add support for feed subscription

### PR DESCRIPTION
**Pull request by xsahil03x**
Fixes: #55, Porting our Dart implementation in Java
https://github.com/GetStream/stream-feed-flutter

A sample usage
```java
// APPID IS REQUIRED IN ORDER TO SUBSCRIBE FEEDS
CloudClient cloudClient = CloudClient.builder(apiKey, token, "chris", appId).build();

CloudFlatFeed chris = cloudClient.flatFeed("user", "chris");

// PRINTS ANY CHANGES IN THE FEED
var subscription = chris.subscribe(message -> System.out.println(message.toString())).get();

chris.addActivity(
      Activity.builder()
              .actor("SU:chris")
              .verb("tweet")
              .object("tweet:10")
              .extraField("message", "Beautiful bird!")
              .build()
     ).get();
     
subscription.cancel();
```

### CODE REVIEW

**Comment by xsahil03x** [comment]
@ferhatelmas I have a different formatting configuration in my IntelliJ, so can you also maybe reformat all and push.

**Comment by ferhatelmas** [comment]
>  can you also maybe reformat all and push.

@xsahil03x don't worry about it, will update CI to do it automatically.

**Comment by ferhatelmas** [comment]
@peterdeme let's review and try to release this

**Review by peterdeme — CHANGES_REQUESTED** [review]
@xsahil03x looks good to me except for my small comment. Can you add tests too?

**Comment by peterdeme** [comment]
@xsahil03x @ferhatelmas I copied the contents of this PR and opened a new one: https://github.com/GetStream/stream-java/pull/110

Please follow that one. @xsahil03x - thanks so much for your contribution 🙏 we'll try to release it ASAP.

**Pull request closed without merging**
