### PR TITLE
feat: add unseen, unread to notificationfeed response

### PR DESCRIPTION
**Pull request by peterdeme**
Including a fix for https://github.com/GetStream/stream-java/issues/101

### CODE REVIEW

**Comment by ferhatelmas** [comment]
@peterdeme can we handle this change in cloud client package ?

**Comment by peterdeme** [comment]
@ferhatelmas I'm not familiar with it, how do I do that?

**Comment by ferhatelmas** [comment]
we need to cover changes here too https://github.com/GetStream/stream-java/blob/main/src/main/java/io/getstream/cloud/CloudNotificationFeed.java

**Comment by peterdeme** [comment]
@ferhatelmas fixed

**Pull request merged**
