### PR TITLE
feat: add capability in batch client to get enrichment activities to use enrichment flags

### PR DESCRIPTION
**Pull request by adinovri**

### CODE REVIEW

**Comment by adinovri** [comment]
Hi @JcMinarro can you help to check?

**Comment by JcMinarro** [comment]
> Hi @JcMinarro can you help to check?

Could you check the tests?
It seems they are failing

**Comment by adinovri** [comment]
The test is missing the API key, the API key should be server, or local server env.

**Comment by adinovri** [comment]
Seems missing the environment variable in CI

`Run ./gradlew spotlessCheck --no-daemon
  ./gradlew spotlessCheck --no-daemon
  ./gradlew test --no-daemon
  shell: /usr/bin/bash -e {0}
  env:
    STREAM_KEY: 
    STREAM_SECRET: 
    STREAM_APP_ID: `

**Comment by adinovri** [comment]
Hi @JcMinarro all the test failed having these errors
`java.lang.IllegalArgumentException: API key can't be empty `

It is the error from the previous test cases.

**Pull request merged**
